### ISSUE TITLE
Contact DBNL for licensing questions

### ISSUE THREAD

**Issue by proycon** [knaw-huc/brieven-van-hooft-pipeline#6]
The license for the original works is (all identical): 
* https://www.dbnl.org/titels/gebruiksvoorwaarden.php?id=hoof001hwva02
* https://www.dbnl.org/titels/gebruiksvoorwaarden.php?id=hoof001hwva03
* https://www.dbnl.org/titels/gebruiksvoorwaarden.php?id=hoof001hwva04

For maximum scientific reproducibility I would like:

1. To make derived works of these three editions, annotated in 2017 (FoLiA XML and the preprocessed plain texts that were the input at the time) available in this repository. These contain substantial excerpts from the original. These are the input for the processing pipeline so storing these properly is most essential.
3. Store in this repo an exact copy of the plain-text versions that are already publicly available from DBNL (e.g https://www.dbnl.org/nieuws/text.php?id=hoof001hwva02), and automatically retrieved by this pipeline:
    * This copy just serves as a fallback in case the upstream version at DBNL changes at some point (I assume the plain text is converted from the TEI version, that convertor may be updated in the future). Such updates would render all existing offsets invalid so a cached copy acts as a fallback. This pipeline, however, can be rerun to obtain new offsets if such a change ever occurs.
4. Make the resulting texts with visualisations (static HTML) publicly available
5. Have a public instance of TextAnnoViz (web application) that researchers can browse to view the full texts and all their annotations.

This needs to be discussed with DBNL.

**Comment by marijnschraagen** [comment]
We have previously tried to talk to DBNL about this, as well as to the 'rechthebbenden', i.e., the publisher of the original book. However, the author is deceased, and the publisher is no longer in business and the legal successor could not provide us with a clear answer on how to proceed. The book is a compilation of the source text by Hooft with annotations and background by the editor (H.W. van Tricht), and our idea was to remove all the 'new' parts (the annotations and background) and be left with the original text of Hooft only, which is arguably not copyrighted. The idea was that this would allow to create derivative works with no permission needed, however it was not entirely clear if that argument is actually valid. If needed I could try to track down our correspondence on this topic with the various parties, however as mentioned before it did not reach a conclusion.

**Comment by proycon** [comment]
@marijnschraagen Ha! Thanks for your input, that is very insightful to know, then we could pick up on where things left off at that time. It's good to know you had in mind that derivative works could be distributed (that makes my point 1 more attainable.)

One of the main things we have done in this project is realign all the annotations you did with the original texts (so including the 'new' parts), which DBNL itself makes publicly available as plain text.

**Comment by hayco** [comment]
Wacht op Marjo van Koppen.

**Comment by hennie** [comment]
Marjo heeft inmiddels antwoord van DNBL: online herpubliceren is ok, zolang het alleen de 17e eeuwse teksten zelf betreft

**Comment by proycon** [comment]
Ok, maar dat betekent dat ik de oorspronkelijke FoLiA's en teksten uit het 2017 project hier dus niet mee mag publiceren, want daar staan ook voetnotes enzo in. Eigenlijk vallen hiermee dus alle vier de punten uit het oorspronkelijke verzoek in het water.

Dat maakt het opnieuw draaien van de pipeline wat lastiger, ik zal een plekje zoeken waar de bijbehorende data dan achter een muurtje gestald kan worden.
